steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/qualtricsinteraction/recraft-image-app', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/qualtricsinteraction/recraft-image-app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'recraft-image-service'
    - '--image'
    - 'gcr.io/qualtricsinteraction/recraft-image-app'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-secrets'
    - 'RECRAFT_API_TOKEN=RECRAFT_API_TOKEN:latest'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '300'
    - '--concurrency'
    - '80'
    - '--min-instances'
    - '1'
    - '--max-instances'
    - '10'
images:
  - 'gcr.io/qualtricsinteraction/recraft-image-app'